# Generated by Django 4.2.4 on 2023-10-11 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_role"),
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="datetime",
        ),
        migrations.AddField(
            model_name="appointment",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="department",
            field=models.CharField(
                choices=[
                    ("PSYCHOLOGY", "Psicologia"),
                    ("NEUROLOGIST", "Neurologista"),
                    ("PEDIATRICIAN", "Pediatra"),
                    ("DENTISTRY", "Odontologia"),
                    ("OPHTHALMOLOGIST", "Oftalmologista"),
                    ("GENERAL_PRACTITIONER", "Clínico Geral"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.doctoruser"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="appointments", to="users.patientuser"
            ),
        ),
    ]
