# Generated by Django 4.2.4 on 2023-10-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0002_remove_appointment_datetime_appointment_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterField(
            model_name="appointment",
            name="department",
            field=models.CharField(
                choices=[
                    ("Psicologia", "Psicologia"),
                    ("Neurologista", "Neurologista"),
                    ("Pediatra", "Pediatra"),
                    ("Odontologia", "Odontologia"),
                    ("Oftalmologista", "Oftalmologista"),
                    ("Clínico Geral", "Clínico Geral"),
                ],
                max_length=20,
            ),
        ),
    ]
